name: Training CI

on:
  pull_request:
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check TypeScript
        run: yarn types

